spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://easybank.cbjdnvwyemo7.us-east-2.rds.amazonaws.com:3306/easybank
    username: admin
    password: 12345678

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true